apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: toolrent
type: Opaque
data:
  # Credenciales para MySQL codificadas en Base64
  # rootpass
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  # toolrent
  MYSQL_USER: dG9vbHJlbnQ=
  # toolrent123
  MYSQL_PASSWORD: dG9vbHJlbnQxMjM=
