apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: toolrent
type: Opaque
stringData:
  # Credenciales para MySQL
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_USER: "toolrent"
  MYSQL_PASSWORD: "toolrent123"
