apiVersion: v1
kind: ConfigMap
metadata:
  name: toolrent-config
  namespace: toolrent
data:
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  CONFIG_SERVER_URL: "http://config-server:8888"
  MYSQL_DATABASE_TOOLS: "tools_db"
  MYSQL_DATABASE_CLIENTS: "clients_db"
  MYSQL_DATABASE_CONFIG: "config_db"
  MYSQL_DATABASE_LOANS: "loans_db"
  MYSQL_DATABASE_KARDEX: "kardex_db"
  # NOTA: La gestión de usuarios (Épica 7) se maneja con Keycloak
